In [5]:
from ollama import Client

model='llama3.1:8b'
client = Client(host='http://localhost:11434')

In [6]:
# Test ollama client
response = client.chat(
    model=model,
    messages=[
        {
            'role': 'user',
            'content': 'Привет! Напиши одно короткое предложение.',
        },
    ],
)
print(response['message']['content'])

Привет! Меня зовут Лукас.

In [7]:
import re
import json

EXPECTED_FIELDS = {
    "product_id",
    "description",
    "pros",
    "cons",
    "tags",
}

MIN_DESCRIPTION_LENGTH = 120 
MAX_DESCRIPTION_LENGTH = 700 


class ResponseValidationError(ValueError):
    """Ошибка парсинга или проверки ответа модели."""


def count_sentences(text):
    """Число предложений в тексте. Точка внутри числа концом предложения не считается."""
    return len([s for s in re.split(r"[.!?]+(?!\d)", text) if s.strip()]) 


def parse_and_validate(content: str, product_id_req: str) -> dict[str, str]:
    """Преобразовать JSON-ответ и проверить его контракт."""

    ret = {"product_id": product_id_req}

    try:
        data = json.loads(content)
    except json.JSONDecodeError as error:
        return ret | {'error': f"Ответ не является корректным JSON: {error.msg}"}

    if not isinstance(data, dict):
        return ret | {'error': "На верхнем уровне должен находиться JSON-объект"}

    received_fields = set(data)
    missing_fields = EXPECTED_FIELDS - received_fields
    unexpected_fields = received_fields - EXPECTED_FIELDS

    if missing_fields:
        return ret | {'error': "Отсутствуют обязательные поля: "
            f"{sorted(missing_fields)}"
        }

    if unexpected_fields:
        return ret | {'error': "Отсутствуют обязательные поля: "
            "Получены лишние поля: "
            f"{sorted(unexpected_fields)}"
        }

    product_id = data['product_id']
    if product_id.strip() != product_id_req.strip():
        return ret | {'error': "Поле product_id не соответствует входным параметрам"}

    description = data["description"]

    if not isinstance(description, str):
        return ret | {'error': "Поле description должно быть строкой"}

    description = description.strip()

    if not description:
        return ret | {'error': "Поле description не должно быть пустым"}
      
    i = count_sentences(description)
    if i < 2 or i > 5:
        return ret | {'error': "Description must contain 2-5 sentences"}

    if len(description) < MIN_DESCRIPTION_LENGTH:
        return ret | {'error': "Отсутствуют обязательные поля: "
            "Поле description содержит больше "
            f"{MAX_DESCRIPTION_LENGTH} символов"
        }

    if len(description) > MAX_DESCRIPTION_LENGTH:
        return ret | {'error': "Поле description содержит меньше "
            f"{MAX_DESCRIPTION_LENGTH} символов"
        }

    pros = data['pros']
    if len(pros) < 2 or len(pros) > 5:
       return ret | {'error': "Поле pros must contain 2-5 values"}

    cons = data['cons']
    if len(cons) < 1 or len(cons) > 3:
       return ret | {'error': "Поле cons must contain 1-3 values"}
    
    tags = data['tags']
    if len(tags) < 3 or len(tags) > 8:
       return ret | {'error': "Поле tags must contain 3-8 values"}
    
    return ret

In [8]:
from typing import List
from typing_extensions import Annotated

from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
)

class CardRequest(BaseModel):
    """Product Card"""

    model_config = ConfigDict(extra="forbid")

    product_id: str = Field(min_length=1, max_length=50)
    description: Annotated[str, Field(min_length=120, max_length=700), AfterValidator(count_sentences)]
    pros: Annotated[List[str], Field(min_length=2, max_length=5)]
    cons: Annotated[List[str], Field(min_length=1, max_length=3)]
    tags: Annotated[List[str], Field(min_length=3, max_length=8)]


    @field_validator("description")
    @classmethod
    def validate_description(cls, value: str) -> str:
      """Удалить внешние пробелы и проверить описание."""
      value = value.strip()

      if not value:
        raise ValueError(
            "Поле summary не должно быть пустым"
        )
      
      i = count_sentences(value)
      if i < 2 or i > 5:
        raise ValueError("Description must contain 2-5 sentences")
      
      return value


    @field_validator('pros')
    @classmethod
    def check_pros(cls, v: List[str]) -> List[str]:
      for i in v:
        if not i.strip():
          raise ValueError("Элементы pros не могут быть пустыми строками")
      return v


    @field_validator('cons')
    @classmethod
    def check_cons(cls, v: List[str]) -> List[str]:
      for i in v:
        if not i.strip():
          raise ValueError("Элементы cons не могут быть пустыми строками")
      return v


    @field_validator('tags')
    @classmethod
    def check_tags(cls, v: List[str]) -> List[str]:
      for i in v:
        if not i.strip():
          raise ValueError("Элементы tags не могут быть пустыми строками")
      return v

In [9]:
response_schema = CardRequest.model_json_schema()
response_schema

{'additionalProperties': False,
 'description': 'Product Card',
 'properties': {'product_id': {'maxLength': 50,
   'minLength': 1,
   'title': 'Product Id',
   'type': 'string'},
  'description': {'maxLength': 700,
   'minLength': 120,
   'title': 'Description',
   'type': 'string'},
  'pros': {'items': {'type': 'string'},
   'maxItems': 5,
   'minItems': 2,
   'title': 'Pros',
   'type': 'array'},
  'cons': {'items': {'type': 'string'},
   'maxItems': 3,
   'minItems': 1,
   'title': 'Cons',
   'type': 'array'},
  'tags': {'items': {'type': 'string'},
   'maxItems': 8,
   'minItems': 3,
   'title': 'Tags',
   'type': 'array'}},
 'required': ['product_id', 'description', 'pros', 'cons', 'tags'],
 'title': 'CardRequest',
 'type': 'object'}

In [10]:
def request_one(
    msg: list[dict], 
    params={"temperature": 0.3, "top_p": 0.9, "top_k": 50, "repetition_penalty": 1.1, "max_tokens": 350}
) -> tuple[str, int]:
  messages=[
    {"role": "system", "content": 
      """
        Generate a product card in Russian (utf-8) by example.
        Example:
        {
          "product_id": "P-1001",
          "description": "Компактные внутриканальные наушники с Bluetooth 5.3 и защитой IPX4. Держат заряд до 24 часов и надёжно сидят при активном движении. Подойдут для спорта и повседневного использования.",
          "pros": ["Чистый звук", "Удобная посадка", "Долгое время работы"],
          "cons": ["Быстро разряжаются на морозе"],
          "tags": ["наушники", "беспроводные", "спорт", "IPX4", "Bluetooth 5.3"]
        } 
        "description": 2-5 sentences,
        return only JSON
      """
    } 
  ] + msg
  # print('>>> messages', messages)

  response = client.chat(
      model=model,  
      messages=messages,
      options={
        'seed':               42,  
        'temperature':        params['temperature'],  
        'top_p':              params['top_p'],
        'max_tokens':         params['max_tokens'],   
        "top_k":              params['top_k'], 
        "repetition_penalty": params['repetition_penalty'],      
      },
      format=CardRequest.model_json_schema(),
  )

  content = response['message']['content']
  if not content:
    raise ResponseValidationError(
        "Empty response of model"
    )

  output_tokens = response.eval_count
  
  return content, output_tokens

In [11]:
import time

def worming_up():
  item = {"product_id": "P-0026", "title": "Смартфон Grafo G9", "category": "Электроника / Смартфоны", "attributes": {"бренд": "Grafo", "экран": "6.7\"", "память": "256 ГБ", "оперативная память": "8 ГБ", "аккумулятор": "6000 мА·ч", "основная камера": "50 Мп"}, "reviews": ["Пользуюсь пару недель. Камера снимает достойно даже вечером", "Брал для себя. Звонки чистые, собеседника слышно хорошо", "В целом Быстро заряжается, за час почти полный", "Заказывал на подарок. Работает шустро, приложения не тормозят", "Брал для себя. Камера мылит фото при недостатке света", "Пользуюсь пару недель. К вечеру заряд просаживается быстрее ожидаемого", "Пользуюсь пару недель. Экран яркий, на солнце всё видно", "Пользуюсь пару недель. Экран яркий, на солнце всё видно", "Пользуюсь каждый день. Экран яркий, на солнце всё видно", "Быстро заряжается, за час почти полный", "В руке лежит удобно, не скользит", "Динамик тихий, в шумном месте плохо слышно", "Работает шустро, приложения не тормозят", "В руке лежит удобно, не скользит", "Коротко: Работает шустро, приложения не тормозят", "Купил на замену старому. Обычный телефон на каждый день, без сюрпризов", "Брал для себя. Батарея держит полтора дня без подзарядки", "В целом Работает шустро, приложения не тормозят"]}

  row_dict = [{"role": "user", "content": f"""{item}"""}]

  started = time.perf_counter()
  resp, tokens = request_one(row_dict)
  generation_time = time.perf_counter() - started

  print('>>> worming_up response, tokens, time:\n', resp, tokens, generation_time)

In [55]:
worming_up()

>>> worming_up response, tokens, time:
 {
  "product_id": "P-0026",
  "description": "Смартфон Grafo G9 - это мощный и функциональный смартфон с большим экраном 6,7 дюймов и мощной основной камерой 50 Мп. Он имеет 256 ГБ внутренней памяти и 8 ГБ оперативной памяти, что позволяет легко хранить и загружать приложения. Аккумулятор имеет емкость 6000 мА·ч, что обеспечивает долгую работу без подзарядки.",
  "pros": ["Чистый звон", "Удобная посадка", "Быстро заряжается", "Работает шустро, приложения не тормозят", "Экран яркий, на солнце всё видно"],
  "cons": ["Динамик тихий, в шумном месте плохо слышно", "Камера мылит фото при недостатке света"],
  "tags": ["Смартфон", "Электроника", "Grafo", "6,7 дюймов", "256 ГБ", "8 ГБ", "6000 мА·ч", "50 Мп"]
} 282 18.439344040991273

In [12]:
MAX_ATTEMPTS = 3 

def generate_one(
    msg: list[dict], 
    product_id: str,
    params={"temperature": 0.3, "top_p": 0.9, "top_k": 50, "repetition_penalty": 1.1, "max_tokens": 350},
) -> tuple[str, int]:
  messages_history = msg.copy()

  counter = 0
  errors = 0
  for attempt in range(1, MAX_ATTEMPTS + 1):
    counter += 1
    content, tokens = request_one(messages_history, params)

    error_dict = parse_and_validate(content, product_id)
    if not 'error' in error_dict:
      return content, tokens
    else:
      errors += 1
      print('>>> error: ', error_dict)
      print('>>> error content: ', content)

      if attempt == MAX_ATTEMPTS:
        return {"product_id": product_id, "error": "ResponseValidationError"}

      messages_history = messages_history + [
        {
          "role": "assistant",
          "content": content,
        },
        {
          "role": "user",
          "content": (
              "Предыдущий ответ не прошёл проверку. "
              f"Причина: {error_dict}. "
              "Исправь ответ и верни только JSON"
          ),
        }
      ]

In [13]:
# test generate_one
item = {
  "product_id": "P-0027", 
  "title": "Пылесос Klin Eco", 
  "category": "Бытовая техника - Пылесосы", "attributes": {"бренд": "Klin", "тип": "с контейнером", "мощность всасывания": "220 Вт", "объём контейнера": "2 л", "время работы": "60 мин", "вес": "1.5 кг"}, 
  "reviews": ["Что могу сказать: Щётка забивается волосами, чистить неудобно", 
                "Насадки удобные, под мебель достаёт легко", 
  ]
}
row_dict = [{"role": "user", "content": f"""{item}"""}]

resp, tokens = generate_one(row_dict, product_id=item['product_id'])
print('>>> resp\n', resp, tokens)

>>> resp
 {
  "product_id": "P-0027",
  "description": "Пылесос Klin Eco - компактный и мощный пылесос с контейнером объемом 2 литра. Он оснащен щеткой, которая легко чистит поверхности, а также насадками для удаления пыли из труднодоступных мест. Пылесос работает от сети 220 Вт и может работать до 60 минут без подзарядки.",
  "pros": ["Удобные насадки", "Легко чистит поверхности", "Мощность всасывания 220 Вт"],
  "cons": ["Щётка забивается волосами"],
  "tags": ["пылесос", "клин", "беспроводные", "с контейнером", "220 Вт"]
} 187

In [14]:
file_name = './dev.jsonl'
with open(file_name, 'r', encoding='utf-8') as file:
  items = file.read().splitlines()

In [15]:
import json
from datetime import datetime
from pathlib import Path

def wright_files(timestamp_str_dir, results, params, df):
  timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
  directory = Path(f"./outputs/{timestamp_str_dir}/{timestamp_str}")
  directory.mkdir(parents=True, exist_ok=True)

  with open(directory / "results.json", "w", encoding="utf-8") as file:
    file.write(results)

  with open(directory / "params.json", "w", encoding="utf-8") as file:
    json.dump(params, file, indent=4, ensure_ascii=False)

  totals_path = f"./outputs/{timestamp_str_dir}" / "totals.csv"
  df.to_csv(totals_path, index=False, encoding="utf-8")

In [17]:
import tiktoken

def token_count_tiktoken(text: str) -> int:
  # Llama 3 использует токенизатор, очень похожий на cl100k_base или o200k_base
  encoding = tiktoken.get_encoding("cl100k_base")
  return len(encoding.encode(text))

In [18]:
# test token_count_tiktoken
tokens = token_count_tiktoken('hello world!')
tokens

3

In [16]:
import json

MAX_TOKENS = 1500

def item_normalize(item: str) -> str:
  item_json = json.loads(item)
  reviews = item_json["reviews"][:30]
  # while token_count_ollama('[' + ", ".join(reviews) + ']') > MAX_TOKENS:
  #    reviews.pop() 

  item_json["reviews"] = reviews
  return json.dumps(item_json, ensure_ascii=False)

In [17]:
item = """
{"product_id": "P-0027", "title": "Пылесос Klin Eco", "category": "Бытовая техника / Пылесосы", "attributes": {"бренд": "Klin", "тип": "с контейнером", "мощность всасывания": "220 Вт", "объём контейнера": "2 л", "время работы": "60 мин", "вес": "1.5 кг"}, "reviews": ["Что могу сказать: Щётка забивается волосами, чистить неудобно", "Насадки удобные, под мебель достаёт легко", "Купил на замену старому. Работает тихо, ребёнка не будит", "Контейнер вытряхивается быстро, руки чистые", "Что могу сказать: Работает тихо, ребёнка не будит", "Пользуюсь каждый день. Насадки удобные, под мебель достаёт легко", "Брал для себя. Лёгкий, руку не устаёт держать", "Насадки удобные, под мебель достаёт легко", "Пользуюсь пару недель. Контейнер вытряхивается быстро, руки чистые", "Брал для себя. Собирает шерсть кота без проблем", "Брали на дачу, для нечастой уборки годится", "Что могу сказать: Работает тихо, ребёнка не будит", "Заказывал на подарок. Работает тихо, ребёнка не будит", "Пользуюсь месяц. Работает тихо, ребёнка не будит", "Купил на замену старому. Насадки удобные, под мебель достаёт легко"]}
"""

item_norm = item_normalize(item)
print('>>> item_norm', item_norm)

>>> item_norm {"product_id": "P-0027", "title": "Пылесос Klin Eco", "category": "Бытовая техника / Пылесосы", "attributes": {"бренд": "Klin", "тип": "с контейнером", "мощность всасывания": "220 Вт", "объём контейнера": "2 л", "время работы": "60 мин", "вес": "1.5 кг"}, "reviews": ["Что могу сказать: Щётка забивается волосами, чистить неудобно", "Насадки удобные, под мебель достаёт легко", "Купил на замену старому. Работает тихо, ребёнка не будит", "Контейнер вытряхивается быстро, руки чистые", "Что могу сказать: Работает тихо, ребёнка не будит", "Пользуюсь каждый день. Насадки удобные, под мебель достаёт легко", "Брал для себя. Лёгкий, руку не устаёт держать", "Насадки удобные, под мебель достаёт легко", "Пользуюсь пару недель. Контейнер вытряхивается быстро, руки чистые", "Брал для себя. Собирает шерсть кота без проблем", "Брали на дачу, для нечастой уборки годится", "Что могу сказать: Работает тихо, ребёнка не будит", "Заказывал на подарок. Работает тихо, ребёнка не будит", "Пользуюсь месяц. Работает тихо, ребёнка не будит", "Купил на замену старому. Насадки удобные, под мебель достаёт легко"]}

In [19]:
import json
from pathlib import Path

def card_save(timestamp_str_dir, card, product_id):
  directory = Path(f"./outputs/{timestamp_str_dir}")
  directory.mkdir(parents=True, exist_ok=True)

  with open(f"{directory}/{product_id}.json", "w", encoding="utf-8") as file:
    file.write(card)


def params_save(timestamp_str_dir, params):
  directory = Path(f"./outputs/{timestamp_str_dir}")
  directory.mkdir(parents=True, exist_ok=True)

  with open(directory / "params.json", "w", encoding="utf-8") as file:
    json.dump(params, file, indent=4, ensure_ascii=False)

In [24]:
import pandas as pd
from datetime import datetime
import time
import json

items_slice = items[:5]

df = pd.DataFrame(columns=["num", "temperature", "top_p", "top_k", "repetition_penalty", "max_tokens", 'error', 'descr_len', 'tokens', 'time_per_item'])

timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")

counter = 0

for temperature in [0.0, 0.3, 0.7]:
  for top_p in [0.9, 1.0]:
    for top_k in [20, 50, None]:
      for repetition_penalty in [1.0, 1.1, 1.2]:
        for max_tokens in [250, 350, 500]:
# for temperature in [0.3]:
#   for top_p in [0.9]:
#     for top_k in [50]:
#       for repetition_penalty in [1.1]:
#         for max_tokens in [350]:
          params = {
            "temperature": temperature, 
            "top_p": top_p, 
            "top_k": top_k, 
            "repetition_penalty": repetition_penalty, 
            "max_tokens": max_tokens,
          }
          for item in items_slice:
            err = 0
            counter += 1

            item_norm = item_normalize(item)
            # print('>>> item_norm', item_norm)

            row_dict = {"role": "user", "content": item_norm}
            item_dict = json.loads(item)

            started = time.perf_counter()
            results, tokens = generate_one([row_dict], product_id=item_dict['product_id'], params=params)
            generation_time = time.perf_counter() - started

            if 'error' in results:
              err = 1
              descr_len = 0
            else:
              results_dict = json.loads(results)
              descr_len = len(results_dict['description'])
              # card_save(timestamp_str, results, item_dict['product_id'])
              
            new_row = {'num': counter} | params | {'error': err, 'descr_len': descr_len, 'tokens': tokens, 'time_per_item': round(generation_time, 2)}
            print(new_row)

            df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
            # wright_files(timestamp_str, results, new_row, df)

{'num': 1, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 8.7}
{'num': 2, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 9.24}
{'num': 3, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 9.03}
{'num': 4, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 9.32}
{'num': 5, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 9.37}
{'num': 6, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 8.74}
{'num': 7, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 9.4}
{'num': 8, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 10.47}
{'num': 9, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 12.22}
{'num': 10, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 15.5}
{'num': 11, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 16.47}
{'num': 12, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 19.4}
{'num': 13, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 20.08}
{'num': 14, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 21.18}
{'num': 15, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 17.79}
{'num': 16, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.63}
{'num': 17, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 15.83}
{'num': 18, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.07}
{'num': 19, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.11}
{'num': 20, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 16.12}
{'num': 21, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.8}
{'num': 22, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.05}
{'num': 23, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.65}
{'num': 24, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 15.83}
{'num': 25, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 16.24}
{'num': 26, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 500, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 14.91}
{'num': 27, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 500, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 15.45}
{'num': 28, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 500, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 15.61}
{'num': 29, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 500, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 15.97}
{'num': 30, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.1, 'max_tokens': 500, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 16.38}
{'num': 31, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 250, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.15}
{'num': 32, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 250, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.23}
{'num': 33, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 250, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 15.47}
{'num': 34, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 250, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.16}
{'num': 35, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 250, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 16.49}
{'num': 36, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 350, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.05}
{'num': 37, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 350, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 15.92}
{'num': 38, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 350, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 15.97}
{'num': 39, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 350, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 17.08}
{'num': 40, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 350, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 17.04}
{'num': 41, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 500, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.55}
{'num': 42, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 500, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 15.97}
{'num': 43, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 500, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.29}
{'num': 44, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 500, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.35}
{'num': 45, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 20, 'repetition_penalty': 1.2, 'max_tokens': 500, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 16.6}
{'num': 46, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.49}
{'num': 47, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.1}
{'num': 48, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.44}
{'num': 49, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.48}
{'num': 50, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 18.06}
{'num': 51, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.73}
{'num': 52, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.11}
{'num': 53, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.32}
{'num': 54, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.6}
{'num': 55, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 17.12}
{'num': 56, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.73}
{'num': 57, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.29}
{'num': 58, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.41}
{'num': 59, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.69}
{'num': 60, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 17.0}
{'num': 61, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.75}
{'num': 62, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.35}
{'num': 63, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.36}
{'num': 64, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.7}
{'num': 65, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 16.98}
{'num': 66, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 16.0}
{'num': 67, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 19.46}
{'num': 68, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 17.85}
{'num': 69, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.46}
{'num': 70, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 16.68}
{'num': 71, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 500, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.65}
{'num': 72, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 500, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.2}
{'num': 73, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 500, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.43}
{'num': 74, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 500, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.75}
{'num': 75, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.1, 'max_tokens': 500, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 17.14}
{'num': 76, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 250, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.8}
{'num': 77, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 250, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.47}
{'num': 78, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 250, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.43}
{'num': 79, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 250, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 17.59}
{'num': 80, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 250, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 17.05}
{'num': 81, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 350, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.87}
{'num': 82, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 350, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.48}
{'num': 83, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 350, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.51}
{'num': 84, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 350, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.87}
{'num': 85, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 350, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 17.13}
{'num': 86, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 500, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.91}
{'num': 87, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 500, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.7}
{'num': 88, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 500, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 17.02}
{'num': 89, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 500, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 16.88}
{'num': 90, 'temperature': 0.0, 'top_p': 0.9, 'top_k': 50, 'repetition_penalty': 1.2, 'max_tokens': 500, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 17.05}
{'num': 91, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.85}
{'num': 92, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 16.7}
{'num': 93, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 16.57}
{'num': 94, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 17.16}
{'num': 95, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 250, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 17.45}
{'num': 96, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 15.98}
{'num': 97, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 17.41}
{'num': 98, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 17.25}
{'num': 99, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 17.13}
{'num': 100, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 350, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 17.37}
{'num': 101, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 16.89}
{'num': 102, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 21.04}
{'num': 103, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 18.4}
{'num': 104, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 17.67}
{'num': 105, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.0, 'max_tokens': 500, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 19.66}
{'num': 106, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 20.01}
{'num': 107, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 17.0}
{'num': 108, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 9.44}
{'num': 109, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 9.29}
{'num': 110, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.1, 'max_tokens': 250, 'error': 0, 'descr_len': 205, 'tokens': 187, 'time_per_item': 9.15}
{'num': 111, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 265, 'tokens': 174, 'time_per_item': 8.54}
{'num': 112, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 257, 'tokens': 180, 'time_per_item': 8.92}
{'num': 113, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 264, 'tokens': 182, 'time_per_item': 8.92}
{'num': 114, 'temperature': 0.0, 'top_p': 0.9, 'top_k': None, 'repetition_penalty': 1.1, 'max_tokens': 350, 'error': 0, 'descr_len': 223, 'tokens': 185, 'time_per_item': 9.05}

In [27]:
df_sorted = df.sort_values(by='time_per_item')
df_sorted

,num,temperature,top_p,top_k,repetition_penalty,max_tokens,error,descr_len,tokens,time_per_item
787,788,0.7,1.0,None,1.1,350,0,184,148,7.26
792,793,0.7,1.0,None,1.1,500,0,184,148,7.27
732,733,0.7,1.0,50,1.0,500,0,184,148,7.36
727,728,0.7,1.0,50,1.0,350,0,184,148,7.37
362,363,0.3,0.9,None,1.0,250,0,188,152,7.43
...,...,...,...,...,...,...,...,...,...,...
439,440,0.3,1.0,20,1.2,250,0,215,199,45.21
424,425,0.3,1.0,20,1.1,250,0,215,199,45.26
489,490,0.3,1.0,50,1.2,350,0,215,199,45.27
429,430,0.3,1.0,20,1.1,350,0,215,199,45.47
419,420,0.3,1.0,20,1.0,500,0,215,199,46.43

In [29]:
df_err = df.sort_values(by='error')
df_err

,num,temperature,top_p,top_k,repetition_penalty,max_tokens,error,descr_len,tokens,time_per_item
0,1,0.0,0.9,20,1.0,250,0,265,174,8.7
533,534,0.3,1.0,None,1.2,350,0,212,168,13.88
534,535,0.3,1.0,None,1.2,350,0,215,199,32.45
535,536,0.3,1.0,None,1.2,500,0,241,191,16.87
536,537,0.3,1.0,None,1.2,500,0,196,193,17.47
...,...,...,...,...,...,...,...,...,...,...
274,275,0.3,0.9,20,1.0,250,0,215,199,27.73
275,276,0.3,0.9,20,1.0,350,0,241,191,13.8
276,277,0.3,0.9,20,1.0,350,0,196,193,14.71
266,267,0.0,1.0,None,1.2,500,0,257,180,11.96
809,810,0.7,1.0,None,1.2,500,0,165,183,11.95

In [ ]:
means = (df.groupby(['temperature', 'top_p', 'top_k', 'repetition_penalty', 'max_tokens'], as_index=False)['time_per_item']
        .mean()
        .sort_values(by='time_per_item')
        .to_csv('./outputs/params_mean_sorted.csv', index=False, encoding='utf-8'))

In [44]:
means

temperature  top_p  top_k  repetition_penalty  max_tokens
0.0          0.9    20     1.0                 250            9.132
                                               350           11.266
                                               500           18.984
                           1.1                 250           15.952
                                               350           16.114
                                                              ...
0.7          1.0    50     1.1                 350           12.288
                                               500           12.248
                           1.2                 250           11.834
                                               350           11.784
                                               500            11.72
Name: time_per_item, Length: 108, dtype: object

In [38]:
# totals_path = Path(f"./outputs/totals_final_{timestamp_str}.csv")
totals_path = Path(f"./outputs/params_sorted.csv")
df_sorted.to_csv(totals_path, index=False, encoding="utf-8")

In [ ]:
totals_path = Path(f"./outputs/totals_final_{timestamp_str}.csv")
df_sorted.to_csv(totals_path, index=False, encoding="utf-8")

In [84]:
# file_name = './dev.jsonl'
file_name = './benchmark.jsonl'
with open(file_name, 'r', encoding='utf-8') as file:
  items = file.read().splitlines()

In [93]:
import time
import json

items_slice = items[:]
timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
err = 0
count = 0

params = {
  "temperature":        0.3, 
  "top_p":              0.9, 
  "top_k":              50, 
  "repetition_penalty": 1.1, 
  "max_tokens":         350,
  "products":           len(items_slice), 
}

# worming_up()

started_batch = time.perf_counter()

for item in items_slice:
  count += 1

  item_norm = item_normalize(item)
  row_dict = {"role": "user", "content": item_norm}
  item_dict = json.loads(item)

  started = time.perf_counter()
  results, tokens = generate_one([row_dict], product_id=item_dict['product_id'], params=params)
  generation_time = time.perf_counter() - started

  if 'error' in results:
    err += 1
  else:
    card_save(timestamp_str, results, item_dict['product_id'])
    
  new_row = {"num": count, 'card': item_dict['product_id'], 'error': err, 'tokens': tokens, 'time_per_item': round(generation_time, 2)}
  print(new_row)

batch_generation_time = round(time.perf_counter() - started_batch, 2)
params_save(
  timestamp_str, 
  params | 
  {
    "errors": err, 
    "error_percent": round(100 * err / len(items_slice), 2), 
    "total_time_sec": batch_generation_time, 
    'time_per_item_sec': round(batch_generation_time / len(items_slice), 2)
  }
)

{'num': 1, 'card': 'P-1144', 'error': 0, 'tokens': 148, 'time_per_item': 7.46}
{'num': 2, 'card': 'P-1057', 'error': 0, 'tokens': 180, 'time_per_item': 9.01}
{'num': 3, 'card': 'P-1261', 'error': 0, 'tokens': 210, 'time_per_item': 10.33}
{'num': 4, 'card': 'P-1237', 'error': 0, 'tokens': 159, 'time_per_item': 10.31}
{'num': 5, 'card': 'P-1281', 'error': 0, 'tokens': 148, 'time_per_item': 8.58}
{'num': 6, 'card': 'P-1155', 'error': 0, 'tokens': 165, 'time_per_item': 9.3}
{'num': 7, 'card': 'P-1076', 'error': 0, 'tokens': 182, 'time_per_item': 12.25}
{'num': 8, 'card': 'P-1258', 'error': 0, 'tokens': 205, 'time_per_item': 16.35}
{'num': 9, 'card': 'P-1075', 'error': 0, 'tokens': 198, 'time_per_item': 15.62}
{'num': 10, 'card': 'P-1148', 'error': 0, 'tokens': 153, 'time_per_item': 16.84}
{'num': 11, 'card': 'P-1149', 'error': 0, 'tokens': 188, 'time_per_item': 25.41}
{'num': 12, 'card': 'P-1106', 'error': 0, 'tokens': 218, 'time_per_item': 28.32}
{'num': 13, 'card': 'P-1054', 'error': 0, 'tokens': 150, 'time_per_item': 21.32}
{'num': 14, 'card': 'P-1104', 'error': 0, 'tokens': 186, 'time_per_item': 24.26}
{'num': 15, 'card': 'P-1183', 'error': 0, 'tokens': 218, 'time_per_item': 23.36}
{'num': 16, 'card': 'P-1267', 'error': 0, 'tokens': 192, 'time_per_item': 21.17}
{'num': 17, 'card': 'P-1111', 'error': 0, 'tokens': 198, 'time_per_item': 23.36}
{'num': 18, 'card': 'P-1071', 'error': 0, 'tokens': 231, 'time_per_item': 27.07}
{'num': 19, 'card': 'P-1068', 'error': 0, 'tokens': 205, 'time_per_item': 23.85}
{'num': 20, 'card': 'P-1179', 'error': 0, 'tokens': 204, 'time_per_item': 24.56}
{'num': 21, 'card': 'P-1041', 'error': 0, 'tokens': 162, 'time_per_item': 18.47}
{'num': 22, 'card': 'P-1182', 'error': 0, 'tokens': 170, 'time_per_item': 20.65}
{'num': 23, 'card': 'P-1088', 'error': 0, 'tokens': 205, 'time_per_item': 26.74}
>>> error:  {'product_id': 'P-1019', 'error': 'Description must contain 2-5 sentences'}
>>> error content:  {
  "product_id": "P-1019",
  "description": "Пылесос Vortem Cyclone 200 - лёгкий и тихий пылесос с мешком, который собирет шерсть кота без проблем и тянет пыль отлично.",
  "pros": ["Лёгкий", "Работает тихо", "Собирает шерсть кота без проблем", "Тянет пыль отлично"],
  "cons": ["Контейнер маленький", "Забивается щётка волосами", "На длинном ворсе мощности не хватает"],
  "tags": ["Пылесос", "Бытовая техника", "Вортер", "Мешок", "150 Вт", "0.5 л", "60 мин", "3 кг"]
}
{'num': 24, 'card': 'P-1019', 'error': 0, 'tokens': 240, 'time_per_item': 47.62}
{'num': 25, 'card': 'P-1025', 'error': 0, 'tokens': 180, 'time_per_item': 26.67}
{'num': 26, 'card': 'P-1012', 'error': 0, 'tokens': 196, 'time_per_item': 27.72}
{'num': 27, 'card': 'P-1253', 'error': 0, 'tokens': 202, 'time_per_item': 24.78}
{'num': 28, 'card': 'P-1184', 'error': 0, 'tokens': 222, 'time_per_item': 26.47}
{'num': 29, 'card': 'P-1256', 'error': 0, 'tokens': 176, 'time_per_item': 20.5}
{'num': 30, 'card': 'P-1031', 'error': 0, 'tokens': 209, 'time_per_item': 27.04}
{'num': 31, 'card': 'P-1240', 'error': 0, 'tokens': 203, 'time_per_item': 26.11}
{'num': 32, 'card': 'P-1181', 'error': 0, 'tokens': 190, 'time_per_item': 21.81}
>>> error:  {'product_id': 'P-1060', 'error': 'Description must contain 2-5 sentences'}
>>> error content:  {
  "product_id": "P-1060",
  "description": "Куртка Polaris демисезонная. Утеплитель - пух. Сезон - зима. Водоотталкивающая пропитка есть. Капюшон съёмный. Температурный режим до -10.",
  "pros": ["Удобный капюшон", "Сидит по фигуре", "Лёгкая для своей теплоты", "Тёплая, в мороз не продувает"],
  "cons": ["Утеплитель сбивается после стирки"],
  "tags": ["куртка", "демонсезонная", "утеплитель пух", "водоотталкивающая пропитка", "съёмный капюшон"]
}
{'num': 33, 'card': 'P-1060', 'error': 0, 'tokens': 223, 'time_per_item': 46.29}
{'num': 34, 'card': 'P-1026', 'error': 0, 'tokens': 186, 'time_per_item': 23.1}
{'num': 35, 'card': 'P-1052', 'error': 0, 'tokens': 207, 'time_per_item': 26.99}
>>> error:  {'product_id': 'P-1229', 'error': 'Description must contain 2-5 sentences'}
>>> error content:  {
  "product_id": "P-1229",
  "description": "Кроссовки Aeron беговые. Дышат хорошо, нога не потеет. Сидят как влитые, ногу не натирают. Выглядят стильно, подходят под всё. Пользуюсь пару недель. Быстро пачкаются, сетка светлая.",
  "pros": ["Дышат хорошо", "Сидят как влитые", "Выглядят стильно"],
  "cons": ["Быстро пачкаются", "Подошва скользит на плитке"],
  "tags": ["кроссовки", "беговые", "аэрон", "обувь"]
}
{'num': 36, 'card': 'P-1229', 'error': 0, 'tokens': 167, 'time_per_item': 36.83}
{'num': 37, 'card': 'P-1213', 'error': 0, 'tokens': 153, 'time_per_item': 19.46}
{'num': 38, 'card': 'P-1215', 'error': 0, 'tokens': 190, 'time_per_item': 21.17}
{'num': 39, 'card': 'P-1086', 'error': 0, 'tokens': 172, 'time_per_item': 20.97}
{'num': 40, 'card': 'P-1089', 'error': 0, 'tokens': 233, 'time_per_item': 29.15}
{'num': 41, 'card': 'P-1166', 'error': 0, 'tokens': 145, 'time_per_item': 18.11}
{'num': 42, 'card': 'P-1205', 'error': 0, 'tokens': 170, 'time_per_item': 23.07}
>>> error:  {'product_id': 'P-1140', 'error': 'Description must contain 2-5 sentences'}
>>> error content:  {
  "product_id": "P-1140",
  "description": "Куртка Norvik демисезонная. Утеплитель: холлофайбер. Сезон: зима. Водоотталкивающая пропитка: есть. Капюшон: нет. Температурный режим: до 0.",
  "pros": ["Капюшон удобный, голову закрывает полностью", "Тёплая, в мороз не продувает", "Цвет как на фото, не линяет после стирки", "Пользуюсь пару недель. Карманы вместительные, руки греют", "Заказывал на подарок. Брал по акции, за эту цену нормально"],
  "cons": ["Молния подклинивает на морозе", "Размер маломерит, лучше брать на размер больше", "В сильный ветер поддувает снизу"],
  "tags": ["куртка", "демисезонная", "Norvik", "холлофайбер", "зима", "водоотталкивающая пропитка", "капюшон"]
}
{'num': 43, 'card': 'P-1140', 'error': 0, 'tokens': 292, 'time_per_item': 55.97}
{'num': 44, 'card': 'P-1061', 'error': 0, 'tokens': 195, 'time_per_item': 25.55}
{'num': 45, 'card': 'P-1072', 'error': 0, 'tokens': 261, 'time_per_item': 31.3}
{'num': 46, 'card': 'P-1259', 'error': 0, 'tokens': 205, 'time_per_item': 23.44}
{'num': 47, 'card': 'P-1189', 'error': 0, 'tokens': 167, 'time_per_item': 18.91}
{'num': 48, 'card': 'P-1146', 'error': 0, 'tokens': 248, 'time_per_item': 28.91}
{'num': 49, 'card': 'P-1092', 'error': 0, 'tokens': 204, 'time_per_item': 24.83}
{'num': 50, 'card': 'P-1002', 'error': 0, 'tokens': 190, 'time_per_item': 23.57}
{'num': 51, 'card': 'P-1196', 'error': 0, 'tokens': 152, 'time_per_item': 19.6}
{'num': 52, 'card': 'P-1174', 'error': 0, 'tokens': 186, 'time_per_item': 20.25}
{'num': 53, 'card': 'P-1127', 'error': 0, 'tokens': 205, 'time_per_item': 22.05}
{'num': 54, 'card': 'P-1157', 'error': 0, 'tokens': 166, 'time_per_item': 17.78}
{'num': 55, 'card': 'P-1160', 'error': 0, 'tokens': 206, 'time_per_item': 26.94}
{'num': 56, 'card': 'P-1018', 'error': 0, 'tokens': 239, 'time_per_item': 27.7}
{'num': 57, 'card': 'P-1227', 'error': 0, 'tokens': 187, 'time_per_item': 21.82}
{'num': 58, 'card': 'P-1030', 'error': 0, 'tokens': 166, 'time_per_item': 21.73}
{'num': 59, 'card': 'P-1220', 'error': 0, 'tokens': 211, 'time_per_item': 24.51}
{'num': 60, 'card': 'P-1050', 'error': 0, 'tokens': 170, 'time_per_item': 19.51}
{'num': 61, 'card': 'P-1272', 'error': 0, 'tokens': 157, 'time_per_item': 18.61}
{'num': 62, 'card': 'P-1192', 'error': 0, 'tokens': 213, 'time_per_item': 25.71}
{'num': 63, 'card': 'P-1279', 'error': 0, 'tokens': 154, 'time_per_item': 18.34}
{'num': 64, 'card': 'P-1143', 'error': 0, 'tokens': 224, 'time_per_item': 27.37}
{'num': 65, 'card': 'P-1114', 'error': 0, 'tokens': 211, 'time_per_item': 28.18}
{'num': 66, 'card': 'P-1113', 'error': 0, 'tokens': 179, 'time_per_item': 20.5}
{'num': 67, 'card': 'P-1260', 'error': 0, 'tokens': 164, 'time_per_item': 22.43}
{'num': 68, 'card': 'P-1176', 'error': 0, 'tokens': 147, 'time_per_item': 19.66}
{'num': 69, 'card': 'P-1065', 'error': 0, 'tokens': 211, 'time_per_item': 26.58}
{'num': 70, 'card': 'P-1185', 'error': 0, 'tokens': 183, 'time_per_item': 25.07}
{'num': 71, 'card': 'P-1198', 'error': 0, 'tokens': 155, 'time_per_item': 19.47}
{'num': 72, 'card': 'P-1169', 'error': 0, 'tokens': 196, 'time_per_item': 25.04}
{'num': 73, 'card': 'P-1214', 'error': 0, 'tokens': 188, 'time_per_item': 25.78}
{'num': 74, 'card': 'P-1001', 'error': 0, 'tokens': 159, 'time_per_item': 18.58}
{'num': 75, 'card': 'P-1118', 'error': 0, 'tokens': 150, 'time_per_item': 19.59}
{'num': 76, 'card': 'P-1195', 'error': 0, 'tokens': 213, 'time_per_item': 24.6}
{'num': 77, 'card': 'P-1121', 'error': 0, 'tokens': 141, 'time_per_item': 20.42}
{'num': 78, 'card': 'P-1100', 'error': 0, 'tokens': 171, 'time_per_item': 18.79}
{'num': 79, 'card': 'P-1152', 'error': 0, 'tokens': 201, 'time_per_item': 26.95}
{'num': 80, 'card': 'P-1270', 'error': 0, 'tokens': 168, 'time_per_item': 20.22}
{'num': 81, 'card': 'P-1251', 'error': 0, 'tokens': 197, 'time_per_item': 27.06}
{'num': 82, 'card': 'P-1300', 'error': 0, 'tokens': 239, 'time_per_item': 28.26}
{'num': 83, 'card': 'P-1194', 'error': 0, 'tokens': 195, 'time_per_item': 22.44}
{'num': 84, 'card': 'P-1242', 'error': 0, 'tokens': 176, 'time_per_item': 23.19}
{'num': 85, 'card': 'P-1043', 'error': 0, 'tokens': 241, 'time_per_item': 25.73}
{'num': 86, 'card': 'P-1244', 'error': 0, 'tokens': 177, 'time_per_item': 22.65}
{'num': 87, 'card': 'P-1200', 'error': 0, 'tokens': 226, 'time_per_item': 25.4}
{'num': 88, 'card': 'P-1015', 'error': 0, 'tokens': 227, 'time_per_item': 25.94}
{'num': 89, 'card': 'P-1249', 'error': 0, 'tokens': 260, 'time_per_item': 33.34}
{'num': 90, 'card': 'P-1293', 'error': 0, 'tokens': 180, 'time_per_item': 20.29}
{'num': 91, 'card': 'P-1150', 'error': 0, 'tokens': 200, 'time_per_item': 25.37}
{'num': 92, 'card': 'P-1283', 'error': 0, 'tokens': 193, 'time_per_item': 23.35}
{'num': 93, 'card': 'P-1257', 'error': 0, 'tokens': 157, 'time_per_item': 19.69}
{'num': 94, 'card': 'P-1078', 'error': 0, 'tokens': 190, 'time_per_item': 21.24}
{'num': 95, 'card': 'P-1197', 'error': 0, 'tokens': 173, 'time_per_item': 19.93}
{'num': 96, 'card': 'P-1208', 'error': 0, 'tokens': 248, 'time_per_item': 31.44}
{'num': 97, 'card': 'P-1277', 'error': 0, 'tokens': 175, 'time_per_item': 24.06}
{'num': 98, 'card': 'P-1039', 'error': 0, 'tokens': 175, 'time_per_item': 24.44}
{'num': 99, 'card': 'P-1243', 'error': 0, 'tokens': 203, 'time_per_item': 24.68}
{'num': 100, 'card': 'P-1193', 'error': 0, 'tokens': 173, 'time_per_item': 20.38}
{'num': 101, 'card': 'P-1191', 'error': 0, 'tokens': 167, 'time_per_item': 21.28}
{'num': 102, 'card': 'P-1298', 'error': 0, 'tokens': 190, 'time_per_item': 23.27}
{'num': 103, 'card': 'P-1059', 'error': 0, 'tokens': 196, 'time_per_item': 24.19}
{'num': 104, 'card': 'P-1053', 'error': 0, 'tokens': 143, 'time_per_item': 17.39}
{'num': 105, 'card': 'P-1223', 'error': 0, 'tokens': 200, 'time_per_item': 22.14}
{'num': 106, 'card': 'P-1129', 'error': 0, 'tokens': 147, 'time_per_item': 17.76}
{'num': 107, 'card': 'P-1186', 'error': 0, 'tokens': 198, 'time_per_item': 21.0}
{'num': 108, 'card': 'P-1175', 'error': 0, 'tokens': 188, 'time_per_item': 23.38}
{'num': 109, 'card': 'P-1239', 'error': 0, 'tokens': 221, 'time_per_item': 28.55}
>>> error:  {'product_id': 'P-1029', 'error': 'Description must contain 2-5 sentences'}
>>> error content:  {
  "product_id": "P-1029",
  "description": "Кроссовки Stride Flex - отличный выбор для спортивного отдыха. Они имеют тонкую стельку, что делает их идеальными для занятий в зале. Материал верха из ткани обеспечивает комфорт и свободу движений. Подошва из резины обеспечивает хороший сцепление с поверхностью. Размерный ряд от 41 до 46 размеров. Фиксация с помощью липучки. Качество прошивки хорошее, ничего не отклеивается.",
  "pros": ["тонкая стелька", "комфорт", "свобода движений", "хороший сцепление", "качество прошивки"],
  "cons": ["подошва скользит на плитке", "задник жёсткий, поначалу натирает пятку"],
  "tags": ["кроссовки", "спорт", "зал", "текстиль", "резина", "липучка"]
}
{'num': 110, 'card': 'P-1029', 'error': 0, 'tokens': 186, 'time_per_item': 48.1}
{'num': 111, 'card': 'P-1008', 'error': 0, 'tokens': 169, 'time_per_item': 20.35}
{'num': 112, 'card': 'P-1295', 'error': 0, 'tokens': 232, 'time_per_item': 31.47}
{'num': 113, 'card': 'P-1162', 'error': 0, 'tokens': 196, 'time_per_item': 22.49}
{'num': 114, 'card': 'P-1131', 'error': 0, 'tokens': 167, 'time_per_item': 19.73}
{'num': 115, 'card': 'P-1236', 'error': 0, 'tokens': 198, 'time_per_item': 28.41}
{'num': 116, 'card': 'P-1233', 'error': 0, 'tokens': 173, 'time_per_item': 21.05}
{'num': 117, 'card': 'P-1096', 'error': 0, 'tokens': 206, 'time_per_item': 27.47}
{'num': 118, 'card': 'P-1134', 'error': 0, 'tokens': 170, 'time_per_item': 29.68}
{'num': 119, 'card': 'P-1037', 'error': 0, 'tokens': 189, 'time_per_item': 25.95}
{'num': 120, 'card': 'P-1230', 'error': 0, 'tokens': 153, 'time_per_item': 20.26}
{'num': 121, 'card': 'P-1122', 'error': 0, 'tokens': 225, 'time_per_item': 27.43}
{'num': 122, 'card': 'P-1289', 'error': 0, 'tokens': 177, 'time_per_item': 21.74}
{'num': 123, 'card': 'P-1090', 'error': 0, 'tokens': 189, 'time_per_item': 27.29}
{'num': 124, 'card': 'P-1299', 'error': 0, 'tokens': 163, 'time_per_item': 20.15}
{'num': 125, 'card': 'P-1128', 'error': 0, 'tokens': 174, 'time_per_item': 24.4}
{'num': 126, 'card': 'P-1082', 'error': 0, 'tokens': 232, 'time_per_item': 29.52}
{'num': 127, 'card': 'P-1033', 'error': 0, 'tokens': 167, 'time_per_item': 27.09}
{'num': 128, 'card': 'P-1235', 'error': 0, 'tokens': 162, 'time_per_item': 22.85}
{'num': 129, 'card': 'P-1287', 'error': 0, 'tokens': 229, 'time_per_item': 31.08}
{'num': 130, 'card': 'P-1095', 'error': 0, 'tokens': 204, 'time_per_item': 24.24}
{'num': 131, 'card': 'P-1105', 'error': 0, 'tokens': 170, 'time_per_item': 25.55}
{'num': 132, 'card': 'P-1047', 'error': 0, 'tokens': 187, 'time_per_item': 21.71}
{'num': 133, 'card': 'P-1063', 'error': 0, 'tokens': 188, 'time_per_item': 20.16}
{'num': 134, 'card': 'P-1125', 'error': 0, 'tokens': 162, 'time_per_item': 22.08}
{'num': 135, 'card': 'P-1141', 'error': 0, 'tokens': 152, 'time_per_item': 18.72}
{'num': 136, 'card': 'P-1079', 'error': 0, 'tokens': 186, 'time_per_item': 25.44}
{'num': 137, 'card': 'P-1221', 'error': 0, 'tokens': 162, 'time_per_item': 19.47}
{'num': 138, 'card': 'P-1231', 'error': 0, 'tokens': 185, 'time_per_item': 21.2}
{'num': 139, 'card': 'P-1055', 'error': 0, 'tokens': 173, 'time_per_item': 25.8}
{'num': 140, 'card': 'P-1187', 'error': 0, 'tokens': 157, 'time_per_item': 22.4}
{'num': 141, 'card': 'P-1017', 'error': 0, 'tokens': 181, 'time_per_item': 21.6}
{'num': 142, 'card': 'P-1276', 'error': 0, 'tokens': 226, 'time_per_item': 25.95}
{'num': 143, 'card': 'P-1171', 'error': 0, 'tokens': 187, 'time_per_item': 21.0}
{'num': 144, 'card': 'P-1269', 'error': 0, 'tokens': 188, 'time_per_item': 22.13}
{'num': 145, 'card': 'P-1094', 'error': 0, 'tokens': 185, 'time_per_item': 21.16}
{'num': 146, 'card': 'P-1170', 'error': 0, 'tokens': 213, 'time_per_item': 26.46}
{'num': 147, 'card': 'P-1217', 'error': 0, 'tokens': 214, 'time_per_item': 27.69}
{'num': 148, 'card': 'P-1022', 'error': 0, 'tokens': 163, 'time_per_item': 22.41}
{'num': 149, 'card': 'P-1097', 'error': 0, 'tokens': 204, 'time_per_item': 24.9}
{'num': 150, 'card': 'P-1101', 'error': 0, 'tokens': 161, 'time_per_item': 21.4}
{'num': 151, 'card': 'P-1241', 'error': 0, 'tokens': 156, 'time_per_item': 20.03}
{'num': 152, 'card': 'P-1291', 'error': 0, 'tokens': 167, 'time_per_item': 20.75}
{'num': 153, 'card': 'P-1224', 'error': 0, 'tokens': 197, 'time_per_item': 27.7}
{'num': 154, 'card': 'P-1178', 'error': 0, 'tokens': 224, 'time_per_item': 30.32}
{'num': 155, 'card': 'P-1264', 'error': 0, 'tokens': 218, 'time_per_item': 29.46}
{'num': 156, 'card': 'P-1172', 'error': 0, 'tokens': 159, 'time_per_item': 23.18}
{'num': 157, 'card': 'P-1278', 'error': 0, 'tokens': 178, 'time_per_item': 21.15}
{'num': 158, 'card': 'P-1040', 'error': 0, 'tokens': 201, 'time_per_item': 24.96}
{'num': 159, 'card': 'P-1080', 'error': 0, 'tokens': 195, 'time_per_item': 28.05}
{'num': 160, 'card': 'P-1290', 'error': 0, 'tokens': 209, 'time_per_item': 27.34}
{'num': 161, 'card': 'P-1112', 'error': 0, 'tokens': 166, 'time_per_item': 26.27}
{'num': 162, 'card': 'P-1085', 'error': 0, 'tokens': 169, 'time_per_item': 22.41}
{'num': 163, 'card': 'P-1165', 'error': 0, 'tokens': 170, 'time_per_item': 25.79}
{'num': 164, 'card': 'P-1058', 'error': 0, 'tokens': 206, 'time_per_item': 28.29}
{'num': 165, 'card': 'P-1280', 'error': 0, 'tokens': 217, 'time_per_item': 32.68}
{'num': 166, 'card': 'P-1051', 'error': 0, 'tokens': 166, 'time_per_item': 21.91}
{'num': 167, 'card': 'P-1147', 'error': 0, 'tokens': 199, 'time_per_item': 26.51}
{'num': 168, 'card': 'P-1115', 'error': 0, 'tokens': 204, 'time_per_item': 28.24}
{'num': 169, 'card': 'P-1123', 'error': 0, 'tokens': 164, 'time_per_item': 24.85}
{'num': 170, 'card': 'P-1045', 'error': 0, 'tokens': 195, 'time_per_item': 28.96}
{'num': 171, 'card': 'P-1234', 'error': 0, 'tokens': 137, 'time_per_item': 20.3}
{'num': 172, 'card': 'P-1024', 'error': 0, 'tokens': 219, 'time_per_item': 27.89}
{'num': 173, 'card': 'P-1282', 'error': 0, 'tokens': 157, 'time_per_item': 18.71}
{'num': 174, 'card': 'P-1133', 'error': 0, 'tokens': 184, 'time_per_item': 27.82}
{'num': 175, 'card': 'P-1109', 'error': 0, 'tokens': 163, 'time_per_item': 19.73}
{'num': 176, 'card': 'P-1119', 'error': 0, 'tokens': 203, 'time_per_item': 25.67}
{'num': 177, 'card': 'P-1038', 'error': 0, 'tokens': 161, 'time_per_item': 20.58}
{'num': 178, 'card': 'P-1069', 'error': 0, 'tokens': 174, 'time_per_item': 22.92}
{'num': 179, 'card': 'P-1177', 'error': 0, 'tokens': 207, 'time_per_item': 30.96}
{'num': 180, 'card': 'P-1132', 'error': 0, 'tokens': 208, 'time_per_item': 31.35}
{'num': 181, 'card': 'P-1084', 'error': 0, 'tokens': 171, 'time_per_item': 27.74}
{'num': 182, 'card': 'P-1117', 'error': 0, 'tokens': 237, 'time_per_item': 34.02}
{'num': 183, 'card': 'P-1164', 'error': 0, 'tokens': 164, 'time_per_item': 23.1}
{'num': 184, 'card': 'P-1190', 'error': 0, 'tokens': 181, 'time_per_item': 24.38}
{'num': 185, 'card': 'P-1032', 'error': 0, 'tokens': 185, 'time_per_item': 24.66}
{'num': 186, 'card': 'P-1070', 'error': 0, 'tokens': 149, 'time_per_item': 18.71}
{'num': 187, 'card': 'P-1004', 'error': 0, 'tokens': 183, 'time_per_item': 23.01}
{'num': 188, 'card': 'P-1077', 'error': 0, 'tokens': 198, 'time_per_item': 28.15}
{'num': 189, 'card': 'P-1296', 'error': 0, 'tokens': 171, 'time_per_item': 24.02}
{'num': 190, 'card': 'P-1081', 'error': 0, 'tokens': 180, 'time_per_item': 21.39}
{'num': 191, 'card': 'P-1023', 'error': 0, 'tokens': 188, 'time_per_item': 26.05}
{'num': 192, 'card': 'P-1049', 'error': 0, 'tokens': 191, 'time_per_item': 25.81}
{'num': 193, 'card': 'P-1056', 'error': 0, 'tokens': 184, 'time_per_item': 27.01}
{'num': 194, 'card': 'P-1238', 'error': 0, 'tokens': 167, 'time_per_item': 18.68}
{'num': 195, 'card': 'P-1199', 'error': 0, 'tokens': 147, 'time_per_item': 21.36}
{'num': 196, 'card': 'P-1021', 'error': 0, 'tokens': 132, 'time_per_item': 18.28}
{'num': 197, 'card': 'P-1010', 'error': 0, 'tokens': 196, 'time_per_item': 22.87}
{'num': 198, 'card': 'P-1011', 'error': 0, 'tokens': 180, 'time_per_item': 24.44}
{'num': 199, 'card': 'P-1154', 'error': 0, 'tokens': 171, 'time_per_item': 22.15}
{'num': 200, 'card': 'P-1108', 'error': 0, 'tokens': 229, 'time_per_item': 20.73}
{'num': 201, 'card': 'P-1159', 'error': 0, 'tokens': 199, 'time_per_item': 14.32}
{'num': 202, 'card': 'P-1110', 'error': 0, 'tokens': 135, 'time_per_item': 9.1}
{'num': 203, 'card': 'P-1135', 'error': 0, 'tokens': 195, 'time_per_item': 13.7}
{'num': 204, 'card': 'P-1103', 'error': 0, 'tokens': 164, 'time_per_item': 10.78}
{'num': 205, 'card': 'P-1212', 'error': 0, 'tokens': 206, 'time_per_item': 20.93}